andres_test_home:
    pattern:  /
    defaults: { _controller: AndresTestBundle:Default:index }
    options:
      expose: true

andres_test_content:
    pattern: /content
    defaults: { _controller: AndresTestBundle:Default:content }
    options:
      expose: true

andres_crear_menu:
    pattern: /crear
    defaults: { _controller: AndresTestBundle:Default:create }
    
andres_mostrar_menu:
    pattern: /mostrar/{id}
    defaults: { _controller: AndresTestBundle:Default:show, id: 1 }
