andres_test_home:
    pattern:  /
    defaults: { _controller: AndresTestBundle:Default:index }
    options:
      expose: true

andres_test_content:
    pattern: /content
    defaults: { _controller: AndresTestBundle:Default:content }
    options:
      expose: true