parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     menusach
    database_user:     root
    database_password: menusach

    mailer_transport:    "gmail"
    mailer_encryption:   "ssl"
    mailer_auth_mode:    "login"
    mailer_host:         "smtp.gmail.com"
    mailer_user:         "menusach@gmail.com"
    mailer_password:     "menusachdswii"

    locale:            en
    secret:            4edeb4a2603057db169a78b115807d9540348196
