# app/config/security.yml
jms_security_extra:
    secure_all_services: false
    expressions: true
security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
      default_provider:
        memory:
          users:
            admin: { password: hola, roles: 'ROLE_ADMIN' }
    firewalls:
      login_firewall:
        pattern: ^/login$
        anonymous: ~
      login_check: { form_login: true }
      secured_area:

        pattern: ^/admin
        security: true

        form_login:
          login_path: /login
          check_path: /login_check

        logout:
          path: user_logout
          target: IndexMenUSACH

        anonymous: ~
#          success_handler: authentication_handler
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
