MenUSACHAnnotations:
    resource: "@MenUSACHBaseBundle/Controller/"
    prefix: /
    type: annotation

IndexMenUSACH:
    pattern: /
    defaults: { _controller: MenUSACHBaseBundle:Default:index}

AdminMenUSACH:
    pattern: /admin/
    defaults: { _controller: MenUSACHBaseBundle:Admin:index}

PropMenUSACH:
    pattern: /prop/
    defaults: { _controller: MenUSACHBaseBundle:Prop:index}

ClienteMenUSACH:
    pattern: /admin/cliente
    defaults: { _controller: MenUSACHBaseBundle:Cliente:index}

PropietarioMenUSACH:
    pattern: /admin/propietario
    defaults: { _controller: MenUSACHBaseBundle:Propietario:index}

IngredienteMenUSACH:
    pattern: /admin/ingrediente
    defaults: { _controller: MenUSACHBaseBundle:Ingrediente:index}

LocalMenUSACH:
    pattern: /admin/local
    defaults: { _controller: MenUSACHBaseBundle:Local:index}

PagoMenUSACH:
    pattern: /admin/tipopago
    defaults: { _controller: MenUSACHBaseBundle:TipoPago:index}

MenuMenUSACH:
    pattern: /prop/menu
    defaults: { _controller: MenUSACHBaseBundle:Menu:index}

LoginProp:
    pattern: /prop/login
    defaults: { _controller: MenUSACHBaseBundle:Security:login }

ContactoMenUSACH:
    pattern: /prop/contacto
    defaults: { _controller: MenUSACHBaseBundle:Contacto:index}
    requirements:
        _method:  GET|POST

LoginAdmin:
    pattern: /admin/login
    defaults: { _controller: MenUSACHBaseBundle:Security:adminlogin }

login_check:
    pattern: /prop/login_check

login_check_admin:
    pattern: /admin/login_check

user_logout:
    pattern: /prop/logout
    defaults: { _controller: MenUSACHBaseBundle:Security:logout }

admin_logout:
    pattern: /admin/logout
    defaults: { _controller: MenUSACHBaseBundle:Security:logout }
