men_usach_base_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MenUSACHBaseBundle:Default:index }

men_usach_create_menu:
    pattern: /menu/crear/
    defaults: { _controller:MenUSACHBaseBundle:Menu:new }