parameters:
#    men_usach_base.example.class: MenUSACH\Bundle\BaseBundle\Example

services:
#    men_usach_base.example:
#        class: %men_usach_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
